### PR TITLE
Fix for issue #31

### PR DESCRIPTION
**Pull request by BorisKozo**
- fixed issue with gulp-hub not loading inner gulp files if the inner module has dependency in gulp
- update obsolete versions of dependencies

### CODE REVIEW

**Comment by BorisKozo** [comment]
Github didn't link to #31 from the title

**Comment by robatron** [comment]
Looks good, thanks!

**Comment by frankwallis** [comment]
Thanks for this, it's published as 0.8.0

**Comment by BorisKozo** [comment]
Thank you.
I think it may ruin a very specific (and IMHO uncommon) flow where there is a major version mismatch between the Gulp versions. If someone complains please ping me and I will try to fix.

**Pull request merged**
